import compression from 'compression';
import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { authRouter } from './routes/authRoutes.js';
import { mediaRouter } from './routes/mediaRoutes.js';
import { projectRouter } from './routes/projectRoutes.js';
import { apiLimiter, corsMiddleware, helmetMiddleware } from './middleware/security.js';
import { errorHandler, notFound } from './middleware/error.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');
export const app = express();
app.disable('x-powered-by');
app.use(helmetMiddleware);
app.use(corsMiddleware);
app.use(compression());
app.use(express.json({ limit: '1mb' }));
app.use(apiLimiter);
app.use(express.static(path.join(root, 'public'), { maxAge: '1h', etag: true }));
app.use('/api/auth', authRouter);
app.use('/api/media', mediaRouter);
app.use('/api', projectRouter);
app.get('/health', (req, res) => res.json({ ok: true }));
app.use(notFound);
app.use(errorHandler);
